CREATE TABLE IF NOT EXISTS archivos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS versiones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  archivo_id INT NOT NULL,
  numero_version INT NOT NULL,
  autor_nombre VARCHAR(100) NOT NULL,
  contenido LONGTEXT NOT NULL,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  es_reversion TINYINT(1) NOT NULL DEFAULT 0,
  FOREIGN KEY (archivo_id) REFERENCES archivos(id) ON DELETE CASCADE,
  INDEX idx_archivo_version (archivo_id, numero_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
